site_name: kubequery
repo_url: https://github.com/lbkolev/kubequery
site_url: https://lbkolev.github.io/kubequery
site_description: Query Kubernetes through SQL
site_author: Lachezar Kolev
edit_uri: edit/main/docs/
repo_name: lbkolev/kubequery
copyright: Maintained by <a href="https://lbkolev.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lbkolev/kubequery
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/kubequery

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true