apiVersion: v1
kind: Pod
metadata:
  name: 'podtemplate'
spec:
  volumes:
    - name: source-data-volume
      emptyDir: {}
    - name: metrics-files-volume
      emptyDir: {}
  nodeSelector:
    eks.amazonaws.com/nodegroup: emr-containers-nodegroup
  containers:
  - name: spark-kubernetes-driver # This will be interpreted as driver Spark main container
    env:
      - name: RANDOM
        value: "random"
    volumeMounts:
      - name: shared-volume
        mountPath: /var/logs
      - name: metrics-files-volume
        mountPath: /var/logs/keybagd.log.0
  - name: custom-side-car-container # Sidecar container
    image: hello-world
    env:
      - name: RANDOM_SIDECAR
        value: random
    volumeMounts:
      - name: metrics-files-volume
        mountPath: /var/metrics/data
    command:
      - /bin/sh
      - '-c'
      - 'ls'
      - '-la'
  initContainers:
  - name: spark-init-container-driver # Init container
    image: hello-world
    volumeMounts:
      - name: source-data-volume # Use EMR predefined volumes
        mountPath: /var/data
    command:
      - /bin/sh
      - '-c'
      - 'ls'
      - '- la'
  
